name: Publish

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: The type of release
        required: true
        type: choice
        options: ["stable", "beta", "alpha"]
      modrinth-mc-version:
        description: The minecraft version on modrinth
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publishMods
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TYPE: ${{ inputs.version-type }}
          GITHUB_BRANCH: ${{ github.ref }}
          MODRINTH_MC_VERSION: ${{ inputs.modrinth-mc-version }}
